### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by akshoelace** [alrova96/UAV-Water-Mosaicking-Code#1]
Is it possible to apply to this code to RGB UAV imagery (no Rrs)?

**Comment by alrova96** [comment]
Yes, we are currently working on updating this code repository with a new mosaicking technique for RGB, thermal, and multispectral imagery. It will be published very soon.

**Comment by akshoelace** [comment]
Hello! Just wondering if there are any updates on your mosaicking for RGB?

**Comment by alrova96** [comment]
Yes, it is currently under review. If you need more specific information about it, please don't hesitate to contact me via email at a.roman@csic.es
